### ISSUE TITLE
How to access the DOM element that generated an event?

### ISSUE THREAD

**Issue by pmontrasio** [AmpersandJS/ampersand-collection-view#26]
I have a CollectionView which renders Game models. A GameView displays two players in the row of a table. I registered "click .player" to catch clicks on the DOM elements displaying the player names. It works and this.model returns the Game object I clicked on. However I can't find how to get to the DOM element. Maybe it's in the documentation and I just can't see it.
In this case there is a workaround, because listening for "click .player-a" and "click .player-b" gives me enough information to implement what I have to do, but in general it would be nice to be able to know which element generated a click or another event.

**Comment by mmacaula** [comment]
@pmontrasio, I may be missing the point of your question, but when you register any kind of events using the [events hash](http://ampersandjs.com/docs#ampersand-view-events) the function you call is passed the dom event.  So:  

```
// view
events : {
'click .player-a' : 'onClick'
},
onClick : function(event){
// event is your DOM event, you can find dom element using  'event.target' or 'event.currentTarget'
}
```

**Comment by pmontrasio** [comment]
I didn't realize that the functions in the event hash are normal event handlers. The examples at https://github.com/AmpersandJS/ampersand-view don't have the event argument. But now that I know it, I noticed ```'click .open': function (e) { ... }``` in the example for delegateEvents. Thank you.
