### ISSUE TITLE
function for model option doesn't properly new up returned view ctor

### ISSUE THREAD

**Issue by engenb** [AmpersandJS/ampersand-collection-view#38]
I'm a little strapped for time right now, or I'd do a pull request for ya

_createViewForModel line 44

you have:
```var view = new this.view(_({model: model, collection: this.collection}).extend(this.viewOptions));```
this doesn't properly construct the view.  the ctor returned from this.view(...) is assigned to local var view.  I think you want:
```var view = new (this.view(_({model: model, collection: this.collection}).extend(this.viewOptions)));```

tested the added parenthesis in the js console and it did the trick

**Comment by gonsfx** [comment]
That line is not in the `master`.

What version are you using?
Tried to update to a more recent version?

**Comment by engenb** [comment]
I had ^1.2.1 in my package.json, which I thought would pull the most recent 1.x.x.  Thought that'd have me on your latest 1.4.0, but maybe I've misunderstood how semver works.  Forced an update to 1.4.0 and it's looking better.  Sorry for the confusion.
