### ISSUE TITLE
1.x => 2.x q

### ISSUE THREAD

**Issue by cdaringe** [AmpersandJS/ampersand-collection-view#45]
hey @lukekarrys, was there a reason this bumped major version?  it seems like the dep swap didn't add any breaking changes or API changes, just some internals.  is that right, or did i miss something?

just making sure because i plan to bump &-view w/ just a patch

**Comment by lukekarrys** [comment]
I talked about it with @wraithgar and thought it would be good for bundling. This way all the latest major versions are using lodash v4 and the previous major versions are using lodash 3, and it would avoid situations were projects would end up with lodash 3 and 4 in their bundles.

**Comment by lukekarrys** [comment]
And at this point a patch would be find view &-view since it was already using lodash 4 and the latest updates just make sure all its dependencies are also using lodash 4.

**Comment by cdaringe** [comment]
touche! thanks

On Thu, May 26, 2016 at 10:50 AM, Luke Karrys <notifications@github.com>
wrote:

> And at this point a patch would be find view &-view since it was already
> using lodash 4 and the latest updates just make sure all its dependencies
> are also using lodash 4.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AmpersandJS/ampersand-collection-view/issues/45#issuecomment-221928957>
>



-- 
Chris Dieringer
p: (503)358-8577
e: cdieringer@mrn.org
w: http://cdaringe.com
